name: CI

on:
  pull_request:
    paths-ignore:
      -  '**.md'
  push:
    branches:
      - "main"
      - "dev"
    paths-ignore:
      -  '**.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
      - run: npm install
      - run: npm run lint
      - run: npm run format-check
